### ISSUE TITLE
Pangeo sprint, Tuesday June 5

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#250]
@jhamman will be visiting NYC before the EarthCube all hands meeting. We are planning some sort of Pangeo sprint on Tuesday, June 5 at the Columbia main campus. All are welcome and encouraged to attend. More details forthcoming.

**Comment by rabernat** [comment]
Tagging some people I would like to have join this: @tjcrone, @naomi-henderson, @chiaral, @raphaeldussin, @roxyboy, @anirban89, @sridge, @mandli.

**Comment by mandli** [comment]
Would love to join but I am going to be doing another NSF thing that day unfortunately.

**Comment by rabernat** [comment]
It sounds like we will have a few Lamont folks, plus Joe, at this little sprint.

I wanted to brainstorm what our priorities should be. Some ideas:

- [ ] Finish up the new website (#229, #230) and launch it
- [ ] Set up the example notebook gallery (#201)
- [ ] Add more example notebooks (@sridge and @naomi-henderson have expressed interest in contributing to this)
- [ ] Add all our existing cloud datasets to the `intake` data catalog (see #39). (This requires https://github.com/pangeo-data/helm-chart/pull/29 to be resolved.)

Any other high priorities that we can check off during an eight-hour sprint?

**Comment by mandli** [comment]
Given that I won't be able to attend this I was a bit curious if there was a slack channel or something similar that is tied to pangeo development in general?  I ask as we are starting to explicitly build in xarray support (and dask by extension) to Clawpack.

**Comment by jhamman** [comment]
@mandli - checkout https://gitter.im/pangeo-data/Lobby

**Comment by mandli** [comment]
Perfect, thanks!

**Comment by mrocklin** [comment]
@mandli I'm glad to hear about the interest from the clawpack community.
Please don't hesitate to reach out.

**Comment by tjcrone** [comment]
I'll be there! I have a lot to add to the documentation which might be a good item to have on our list. @rabernat, should we try to get a room in DSI? If this is not possible, there are great spaces in Lerner. How many people do we think we will have?

**Comment by rabernat** [comment]
The location for the sprint will be the DEES conference room on the 5th floor of the Schermerhorn Extension. I will be there by 9am. Anyone is welcome to join for any portion of the day. We will order pizza or something for lunch.

@jhamman -- this is the same building where we had the first Pangeo workshop, but the room is different. To reach the extension, go to the stairwell in the back right corner and then up one floor. 

![schermerhorn](http://library.columbia.edu/content/libraryweb/locations/geology/directions/_jcr_content/layout_par_main_1/image_v2.img.png/1476487366066.png)

**Comment by mrocklin** [comment]
How did things go?

**Comment by rabernat** [comment]
We had a great session with @jhamman, @tjcrone, @naomi-henderson, @sridge, and @chiaral.

Everyone presented their current use cases, and we discussed common stumbling blocks. This led to a few new github issues:
- xarray: tolerance for assignment - https://github.com/pydata/xarray/issues/2217. This is related to @naomi-henderson's efforts to prepare CMIP5 data for analysis 
- dask: Dask spills to disk despite disabling in config - https://github.com/dask/dask/issues/3565. This is related to @srdige's efforts to analyze LENS data on cheyenne

We also got some new contributions to our use-case gallery:
- @sridge's LENS workflow: https://github.com/pangeo-data/pangeo/pull/286/files
- @tjcrone is working on an example of deep sea image data analysis
- @chiaral is working on an example of loading GRIB data

On the technical side, @tjcrone and @jhamman made some exiting progress on integrating binder with pangeo (#283). Joe and I are also pushing hard on the documentation. We plan to launch the new site today.

**Comment by tjcrone** [comment]
Also during pizza-sprint there was some discussion of Google Drive as a place to store data, since many people with academic accounts have unlimited storage on Drive. I have been playing with [this](https://github.com/astrada/google-drive-ocamlfuse) today, configuring it according to [these instructions](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization), and I'm finding that it works really well, and is relatively fast. I'm getting about 400 mb/s transfers from my Drive storage into a stand-alone GCE VM. Not sure how it would scale across a cluster. I have noticed that there may be a [bug](https://github.com/astrada/google-drive-ocamlfuse/issues/448) that could potentially cause the cache to grow very large which would be bad, but it's nothing that rm cannot fix. Anyway, I can envision many beneficial uses of this for Pangeo users.

**Comment by rabernat** [comment]
Tim, would you consider posting the Google Drive idea as a standalone issue?
